const { v4: uuidv4 } = require("uuid");

const skills = [
  {
    id: uuidv4(),
    name: "Software Development",
    skills: [
      "JavaScript",
      "Python",
      "Java",
      "C++",
      "Ruby",
      "React",
      "Angular",
      "Node.js",
      "HTML",
      "CSS",
      "TypeScript",
      "Git",
      "SQL",
      "NoSQL",
      "Agile Methodology",
      "Web Development",
      "Redux",
      "React Hooks",
      "Next.js",
      "Styled Components",
      "State Management",
      "Express.js",
      "Vue.js",
      "Flux",
      "Functional Components",
      "Class Components",
      "AWS",
      "Docker",
      "Unit Testing",
      "Jest",
      "Jenkins",
      "GraphQL",
      "REST APIs",
      "Microservices",
      "Kubernetes",
      "Terraform",
      "CI/CD",
      "SASS/SCSS",
      "Bootstrap",
      "Tailwind CSS",
      "Webpack",
      "Babel",
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "C#",
      "PHP",
      "Go",
      "Kotlin",
      "Swift",
      "Objective-C",
      "Ruby on Rails",
      "Spring Boot",
      "Hibernate",
      "Django",
      "Flask",
      "ASP.NET",
      "TypeORM",
      "Prisma",
      "Electron",
      "TensorFlow",
      "PyTorch",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Machine Learning",
      "Data Science",
      "TDD (Test-Driven Development)",
      "BDD (Behavior-Driven Development)",
      "UI/UX Design",
      "Design Patterns",
      "Software Architecture",
      "SOLID Principles",
      "Clean Code",
      "Continuous Integration",
      "Continuous Deployment",
      "DevOps",
      "Security Best Practices",
      "OAuth",
      "OpenID Connect",
      "WebSockets",
      "gRPC",
      "Event-Driven Architecture",
      "Serverless Computing",
      "Firebase",
      "Azure",
      "Google Cloud Platform (GCP)",
      "Electron",
      "Flutter",
      "React Native",
      "Apache Kafka",
      "RabbitMQ",
      "Elasticsearch",
      "Redis",
      "Graph Databases",
      "Blockchain",
      "Ethereum",
      "Solidity",
      "Smart Contracts",
      "Rust",
      "WebAssembly",
    ],
  },
  {
    id: uuidv4(),
    name: "Data Science",
    skills: [
      "Python",
      "R",
      "SQL",
      "Machine Learning",
      "Deep Learning",
      "Data Visualization",
      "Pandas",
      "NumPy",
      "TensorFlow",
      "PyTorch",
      "Statistics",
      "Data Mining",
      "Big Data",
      "Hadoop",
      "Spark",
      "Power BI",
      "Prompt Engineering",
      "Natural Language Processing (NLP)",
      "Computer Vision",
      "Time Series Analysis",
      "Data Wrangling",
      "Scikit-Learn",
      "Matplotlib",
      "Seaborn",
      "Keras",
      "Data Cleaning",
      "Data Warehousing",
      "Feature Engineering",
      "AWS",
      "Azure",
      "Google Cloud Platform (GCP)",
      "Airflow",
      "ETL (Extract, Transform, Load)",
      "Reinforcement Learning",
      "Bayesian Analysis",
      "Mathematical Optimization",
      "A/B Testing",
      "Hypothesis Testing",
      "Monte Carlo Simulation",
      "Alteryx",
      "Excel",
      "Tableau",
      "D3.js",
      "SAS",
      "Jupyter Notebooks",
      "Git",
      "Data Governance",
      "Data Ethics",
      "Business Analysis",
    ],
  },
  {
    id: uuidv4(),
    name: "Product Management",
    skills: [
      "Agile Methodology",
      "Scrum",
      "User Research",
      "Product Roadmaps",
      "Market Analysis",
      "Stakeholder Management",
      "Wireframing",
      "Prototyping",
      "A/B Testing",
      "User Experience (UX)",
      "Data Analysis",
      "Leadership",
      "Communication",
      "Project Planning",
      "Risk Management",
      "Budget Management",
      "Time Management",
      "Resource Allocation",
      "Team Management",
      "Change Management",
      "Problem Solving",
      "Conflict Resolution",
      "Quality Assurance",
      "Process Improvement",
      "Requirements Gathering",
      "Gantt Charting",
      "Task Prioritization",
      "Decision Making",
      "Dependency Tracking",
      "KPI Tracking",
      "Scope Management",
      "Critical Thinking",
      "Negotiation",
      "Client Management",
      "Project Scheduling",
      "Meeting Facilitation",
      "Strategic Planning",
      "Work Breakdown Structure (WBS)",
      "Risk Mitigation",
      "Project Documentation",
    ],
  },
  {
    id: uuidv4(),
    name: "Customer Support",
    skills: [
      "Customer Service",
      "Communication",
      "Problem Solving",
      "CRM Software",
      "Technical Support",
      "Time Management",
      "Multitasking",
      "Active Listening",
      "Conflict Resolution",
      "Empathy",
      "Knowledge Base Management",
      "Phone Support",
      "Email Support",
      "Patience",
      "Product Knowledge",
      "Positive Attitude",
      "Adaptability",
      "Customer Relationship Management",
      "Attention to Detail",
      "Team Collaboration",
      "Written Communication",
      "Customer Feedback Analysis",
      "Call Center Management",
      "Help Desk Support",
      "Technical Writing",
      "Interpersonal Skills",
      "Decision-Making",
      "Service Level Agreement (SLA) Management",
      "Customer Retention",
      "De-escalation Techniques",
    ],
  },
  {
    id: uuidv4(),
    name: "Human Resources",
    skills: [
      "Recruitment",
      "Employee Relations",
      "HRIS",
      "Onboarding",
      "Payroll",
      "Performance Management",
      "Training & Development",
      "Compliance",
      "Compensation & Benefits",
      "Conflict Resolution",
      "Organizational Development",
      "Talent Management",
      "Employee Engagement",
      "Succession Planning",
      "Labor Law",
      "Diversity & Inclusion",
      "Workforce Planning",
      "HR Analytics",
      "Change Management",
      "Employee Retention",
      "Strategic HR",
      "Employment Law",
      "HR Policy Development",
      "Mediation",
      "Benefits Administration",
      "Health & Safety",
      "Industrial Relations",
      "Employee Satisfaction",
      "Cultural Competency",
      "Job Analysis",
      "Exit Interviews",
      "HR Auditing",
      "People Management",
      "Leadership Development",
      "Coaching & Mentoring",
      "Compensation Analysis",
      "Interviewing",
      "Team Building",
      "Employee Wellness Programs",
      "HR Strategy",
      "Administration",
    ],
  },
  {
    id: uuidv4(),
    name: "Finance",
    skills: [
      "Financial Analysis",
      "Budgeting",
      "Accounting",
      "Financial Modeling",
      "Excel",
      "Risk Management",
      "Investment Analysis",
      "Taxation",
      "Corporate Finance",
      "Audit",
      "Compliance",
      "Financial Reporting",
      "Financial Planning",
      "Cash Flow Management",
      "Cost Accounting",
      "Mergers and Acquisitions (M&A)",
      "Valuation",
      "Portfolio Management",
      "Treasury Management",
      "Financial Forecasting",
      "Internal Controls",
      "Statutory Reporting",
      "Capital Markets",
      "Credit Analysis",
      "Derivatives",
      "Equity Research",
      "Fixed Income Analysis",
      "Pension Fund Management",
      "Hedge Fund Management",
      "Wealth Management",
      "Financial Risk Analysis",
      "Tax Planning",
      "Budget Forecasting",
      "Forensic Accounting",
      "Corporate Governance",
      "Due Diligence",
      "Asset Management",
      "Liquidity Management",
      "Cost-Benefit Analysis",
      "Regulatory Reporting",
      "Financial Compliance",
      "International Finance",
      "Quantitative Analysis",
    ],
  },
];
module.exports = {
  skills,
};
