const { v4: uuidv4 } = require("uuid");

const skills = [
  {
    id: uuidv4(),
    name: "Software Development",
    skills: [
      "JavaScript",
      "Python",
      "Java",
      "C++",
      "Ruby",
      "React",
      "Angular",
      "Node.js",
      "HTML",
      "CSS",
      "TypeScript",
      "Git",
      "SQL",
      "NoSQL",
      "Agile Methodology",
      "Web Development",
      "Redux",
      "React Hooks",
      "Next.js",
      "Styled Components",
      "State Management",
      "Express.js",
      "Vue.js",
      "Flux",
      "Functional Components",
      "Class Components",
      "AWS",
      "Docker",
      "Unit Testing",
      "Jest",
      "Jenkins",
      "GraphQL",
      "REST APIs",
      "Microservices",
      "Kubernetes",
      "Terraform",
      "CI/CD",
      "SASS/SCSS",
      "Bootstrap",
      "Tailwind CSS",
      "Webpack",
      "Babel",
      "MongoDB",
      "PostgreSQL",
      "MySQL",
      "C#",
      "PHP",
      "Go",
      "Kotlin",
      "Swift",
      "Objective-C",
      "Ruby on Rails",
      "Spring Boot",
      "Hibernate",
      "Django",
      "Flask",
      "ASP.NET",
      "TypeORM",
      "Prisma",
      "Electron",
      "TensorFlow",
      "PyTorch",
      "Pandas",
      "NumPy",
      "Scikit-learn",
      "Machine Learning",
      "Data Science",
      "TDD (Test-Driven Development)",
      "BDD (Behavior-Driven Development)",
      "UI/UX Design",
      "Design Patterns",
      "Software Architecture",
      "SOLID Principles",
      "Clean Code",
      "Continuous Integration",
      "Continuous Deployment",
      "DevOps",
      "Security Best Practices",
      "OAuth",
      "OpenID Connect",
      "WebSockets",
      "gRPC",
      "Event-Driven Architecture",
      "Serverless Computing",
      "Firebase",
      "Azure",
      "Google Cloud Platform (GCP)",
      "Flutter",
      "React Native",
      "Apache Kafka",
      "RabbitMQ",
      "Elasticsearch",
      "Redis",
      "Graph Databases",
      "Blockchain",
      "Ethereum",
      "Solidity",
      "Smart Contracts",
      "Rust",
      "WebAssembly",
    ],
  },
  {
    id: uuidv4(),
    name: "Data Science",
    skills: [
      "Python",
      "R",
      "SQL",
      "Machine Learning",
      "Deep Learning",
      "Data Visualization",
      "Pandas",
      "NumPy",
      "TensorFlow",
      "PyTorch",
      "Statistics",
      "Data Mining",
      "Big Data",
      "Hadoop",
      "Spark",
      "Power BI",
      "Prompt Engineering",
      "Natural Language Processing (NLP)",
      "Computer Vision",
      "Time Series Analysis",
      "Data Wrangling",
      "Scikit-Learn",
      "Matplotlib",
      "Seaborn",
      "Keras",
      "Data Cleaning",
      "Data Warehousing",
      "Feature Engineering",
      "AWS",
      "Azure",
      "Google Cloud Platform (GCP)",
      "Airflow",
      "ETL (Extract, Transform, Load)",
      "Reinforcement Learning",
      "Bayesian Analysis",
      "Mathematical Optimization",
      "A/B Testing",
      "Hypothesis Testing",
      "Monte Carlo Simulation",
      "Alteryx",
      "Excel",
      "Tableau",
      "D3.js",
      "SAS",
      "Jupyter Notebooks",
      "Git",
      "Data Governance",
      "Data Ethics",
      "Business Analysis",
    ],
  },
  {
    id: uuidv4(),
    name: "Product Management",
    skills: [
      "Agile Methodology",
      "Scrum",
      "User Research",
      "Product Roadmaps",
      "Market Analysis",
      "Stakeholder Management",
      "Wireframing",
      "Prototyping",
      "A/B Testing",
      "User Experience (UX)",
      "Data Analysis",
      "Leadership",
      "Communication",
      "Project Planning",
      "Risk Management",
      "Budget Management",
      "Time Management",
      "Resource Allocation",
      "Team Management",
      "Change Management",
      "Problem Solving",
      "Conflict Resolution",
      "Quality Assurance",
      "Process Improvement",
      "Requirements Gathering",
      "Gantt Charting",
      "Task Prioritization",
      "Decision Making",
      "Dependency Tracking",
      "KPI Tracking",
      "Scope Management",
      "Critical Thinking",
      "Negotiation",
      "Client Management",
      "Project Scheduling",
      "Meeting Facilitation",
      "Strategic Planning",
      "Work Breakdown Structure (WBS)",
      "Risk Mitigation",
      "Project Documentation",
    ],
  },
  {
    id: uuidv4(),
    name: "Customer Support",
    skills: [
      "Customer Service",
      "Communication",
      "Problem Solving",
      "CRM Software",
      "Technical Support",
      "Time Management",
      "Multitasking",
      "Active Listening",
      "Conflict Resolution",
      "Empathy",
      "Knowledge Base Management",
      "Phone Support",
      "Email Support",
      "Patience",
      "Product Knowledge",
      "Positive Attitude",
      "Adaptability",
      "Customer Relationship Management",
      "Attention to Detail",
      "Team Collaboration",
      "Written Communication",
      "Customer Feedback Analysis",
      "Call Center Management",
      "Help Desk Support",
      "Technical Writing",
      "Interpersonal Skills",
      "Decision-Making",
      "Service Level Agreement (SLA) Management",
      "Customer Retention",
      "De-escalation Techniques",
    ],
  },
  {
    id: uuidv4(),
    name: "Human Resources",
    skills: [
      "Recruitment",
      "Employee Relations",
      "HRIS",
      "Onboarding",
      "Payroll",
      "Performance Management",
      "Training & Development",
      "Compliance",
      "Compensation & Benefits",
      "Conflict Resolution",
      "Organizational Development",
      "Talent Management",
      "Employee Engagement",
      "Succession Planning",
      "Labor Law",
      "Diversity & Inclusion",
      "Workforce Planning",
      "HR Analytics",
      "Change Management",
      "Employee Retention",
      "Strategic HR",
      "Employment Law",
      "HR Policy Development",
      "Mediation",
      "Benefits Administration",
      "Health & Safety",
      "Industrial Relations",
      "Employee Satisfaction",
      "Cultural Competency",
      "Job Analysis",
      "Exit Interviews",
      "HR Auditing",
      "People Management",
      "Leadership Development",
      "Coaching & Mentoring",
      "Compensation Analysis",
      "Interviewing",
      "Team Building",
      "Employee Wellness Programs",
      "HR Strategy",
      "Administration",
    ],
  },
  {
    id: uuidv4(),
    name: "Finance",
    skills: [
      "Financial Analysis",
      "Budgeting",
      "Accounting",
      "Financial Modeling",
      "Excel",
      "Risk Management",
      "Investment Analysis",
      "Taxation",
      "Corporate Finance",
      "Audit",
      "Compliance",
      "Financial Reporting",
      "Financial Planning",
      "Cash Flow Management",
      "Cost Accounting",
      "Mergers and Acquisitions (M&A)",
      "Valuation",
      "Portfolio Management",
      "Treasury Management",
      "Financial Forecasting",
      "Internal Controls",
      "Statutory Reporting",
      "Capital Markets",
      "Credit Analysis",
      "Derivatives",
      "Equity Research",
      "Fixed Income Analysis",
      "Pension Fund Management",
      "Hedge Fund Management",
      "Wealth Management",
      "Financial Risk Analysis",
      "Tax Planning",
      "Budget Forecasting",
      "Forensic Accounting",
      "Corporate Governance",
      "Due Diligence",
      "Asset Management",
      "Liquidity Management",
      "Cost-Benefit Analysis",
      "Regulatory Reporting",
      "Financial Compliance",
      "International Finance",
      "Quantitative Analysis",
    ],
  },
  {
    id: uuidv4(),
    name: "Marketing",
    skills: [
      "Digital Marketing",
      "SEO",
      "Content Marketing",
      "Social Media Management",
      "Email Marketing",
      "PPC Advertising",
      "Marketing Analytics",
      "Brand Management",
      "Market Research",
      "Campaign Management",
      "Affiliate Marketing",
      "Influencer Marketing",
      "Marketing Strategy",
      "Conversion Rate Optimization",
      "Lead Generation",
      "Google Analytics",
      "Customer Segmentation",
      "Graphic Design",
      "Copywriting",
      "PR & Media Relations",
      "Event Planning",
      "Sales Enablement",
      "Product Marketing",
      "Competitive Analysis",
      "Marketing Automation",
      "Budget Management",
      "Customer Retention",
      "Creative Strategy",
      "Market Positioning",
      "Website Optimization",
      "A/B Testing",
      "Customer Insights",
      "Brand Development",
      "Sales Funnel Management",
      "Video Marketing",
      "Mobile Marketing",
      "Content Strategy",
      "Data-Driven Marketing",
      "ROI Analysis",
      "Strategic Partnerships",
    ],
  },
  {
    id: uuidv4(),
    name: "Sales",
    skills: [
      "Lead Generation",
      "Sales Strategy",
      "Account Management",
      "Customer Relationship Management (CRM)",
      "Negotiation",
      "Sales Forecasting",
      "Cold Calling",
      "Pipeline Management",
      "Sales Presentations",
      "Client Acquisition",
      "Sales Reporting",
      "Market Research",
      "Sales Enablement",
      "Customer Retention",
      "Sales Training",
      "Upselling",
      "Cross-Selling",
      "Quota Management",
      "Deal Closure",
      "Sales Prospecting",
      "Sales Automation",
      "Customer Insights",
      "Sales Analytics",
      "Product Knowledge",
      "Competitive Analysis",
      "Networking",
      "Sales Planning",
      "Relationship Building",
      "Consultative Selling",
      "Sales Processes",
      "Key Account Management",
      "Territory Management",
      "Sales Metrics",
      "Customer Service",
      "Contract Negotiation",
      "Sales Campaigns",
      "Revenue Growth",
      "Client Management",
    ],
  },
  {
    id: uuidv4(),
    name: "Design",
    skills: [
      "Graphic Design",
      "UI/UX Design",
      "Adobe Creative Suite",
      "Sketch",
      "Figma",
      "Wireframing",
      "Prototyping",
      "Design Thinking",
      "Typography",
      "Color Theory",
      "User Research",
      "User Testing",
      "Interaction Design",
      "Visual Design",
      "Responsive Design",
      "Brand Identity",
      "Layout Design",
      "Illustration",
      "Photo Editing",
      "InVision",
      "Axure",
      "Web Design",
      "Mobile Design",
      "Creative Direction",
      "Information Architecture",
      "Usability Testing",
      "Content Strategy",
      "Design Systems",
      "Storyboarding",
      "Design Prototyping",
      "Figma Plugins",
      "Design Mockups",
      "Digital Illustration",
      "Visual Communication",
      "Adobe XD",
      "Photoshop",
      "Illustrator",
      "InDesign",
      "Accessibility Design",
      "Design Collaboration",
    ],
  },
  {
    id: uuidv4(),
    name: "Engineering",
    skills: [
      "Software Engineering",
      "Systems Design",
      "Algorithm Design",
      "Data Structures",
      "Code Review",
      "System Architecture",
      "Embedded Systems",
      "Cloud Engineering",
      "DevOps",
      "Continuous Integration",
      "Continuous Deployment",
      "Microservices",
      "API Development",
      "Infrastructure Management",
      "Database Design",
      "Performance Optimization",
      "Security Engineering",
      "Scalability",
      "Code Quality",
      "Unit Testing",
      "Integration Testing",
      "Automated Testing",
      "Configuration Management",
      "System Integration",
      "Technical Documentation",
      "Project Management",
      "Agile Methodology",
      "Software Development Life Cycle (SDLC)",
      "Debugging",
      "Software Design Patterns",
      "Version Control",
      "Deployment Pipelines",
      "Containerization",
      "Serverless Computing",
      "Cloud Platforms (AWS, Azure, GCP)",
      "Network Security",
      "Technical Support",
      "Incident Management",
    ],
  },
  {
    id: uuidv4(),
    name: "Operations",
    skills: [
      "Process Optimization",
      "Supply Chain Management",
      "Logistics",
      "Project Management",
      "Vendor Management",
      "Quality Assurance",
      "Inventory Management",
      "Operational Strategy",
      "Risk Management",
      "Data Analysis",
      "Resource Allocation",
      "Workflow Improvement",
      "Performance Metrics",
      "Operational Efficiency",
      "Cost Reduction",
      "Change Management",
      "Budget Management",
      "Business Continuity Planning",
      "Lean Management",
      "Six Sigma",
      "KPIs",
      "Business Process Reengineering",
      "Capacity Planning",
      "Compliance",
      "Operational Reporting",
      "Problem Solving",
      "Team Management",
      "Negotiation",
      "Stakeholder Management",
      "Contract Management",
      "Strategic Planning",
      "Technology Implementation",
      "Process Mapping",
      "Performance Improvement",
      "Operational Risk Assessment",
    ],
  },
  {
    id: uuidv4(),
    name: "Legal",
    skills: [
      "Legal Research",
      "Contract Drafting",
      "Compliance",
      "Litigation",
      "Corporate Law",
      "Intellectual Property",
      "Legal Writing",
      "Negotiation",
      "Regulatory Affairs",
      "Legal Analysis",
      "Due Diligence",
      "Risk Management",
      "Legal Consulting",
      "Legal Advice",
      "Employment Law",
      "Mergers and Acquisitions (M&A)",
      "Legal Documentation",
      "Legal Compliance",
      "Privacy Law",
      "Corporate Governance",
      "Arbitration",
      "Dispute Resolution",
      "Tax Law",
      "Real Estate Law",
      "Commercial Law",
      "Family Law",
      "Civil Rights Law",
      "Legal Research and Analysis",
      "Litigation Support",
      "Legal Ethics",
      "Court Appearances",
      "Regulatory Compliance",
      "Case Management",
      "Legal Strategy",
      "Legal Risk Assessment",
      "Drafting Agreements",
      "Client Representation",
      "Judicial Procedures",
    ],
  },
  {
    id: uuidv4(),
    name: "Healthcare",
    skills: [
      "Patient Care",
      "Medical Coding",
      "Electronic Health Records (EHR)",
      "Clinical Documentation",
      "Healthcare Management",
      "Medical Billing",
      "Healthcare Compliance",
      "Patient Communication",
      "Medical Terminology",
      "Healthcare Data Analysis",
      "Health Informatics",
      "Medical Research",
      "Pharmacy Management",
      "Nursing Care",
      "Healthcare Policy",
      "Quality Improvement",
      "Patient Safety",
      "Healthcare Administration",
      "Medical Insurance",
      "Health Education",
      "Care Coordination",
      "Population Health Management",
      "Clinical Trials",
      "Healthcare IT",
      "Telemedicine",
      "Health Records Management",
      "Disease Management",
      "Healthcare Operations",
      "Medical Equipment Management",
      "Public Health",
      "Medical Transcription",
      "Patient Advocacy",
      "Healthcare Analytics",
      "Clinical Support",
      "Health Counseling",
      "Medical Research and Analysis",
    ],
  },
  {
    id: uuidv4(),
    name: "Education",
    skills: [
      "Curriculum Development",
      "Instructional Design",
      "Classroom Management",
      "Educational Technology",
      "Lesson Planning",
      "Student Assessment",
      "Educational Assessment",
      "Teaching Strategies",
      "Educational Psychology",
      "Online Teaching",
      "Student Engagement",
      "Academic Advising",
      "Professional Development",
      "Educational Leadership",
      "Special Education",
      "Classroom Instruction",
      "Educational Research",
      "Pedagogy",
      "Educational Policy",
      "Instructional Technology",
      "Teacher Training",
      "Education Administration",
      "Student Support Services",
      "Educational Counseling",
      "Educational Evaluation",
      "Learning Outcomes",
      "Instructional Methods",
      "Distance Education",
      "Education Management",
      "Educational Program Management",
      "Curriculum Evaluation",
      "Educational Content Creation",
      "Student Motivation",
      "Educational Equity",
      "Academic Performance Tracking",
      "Learning Needs Assessment",
      "Educational Standards",
    ],
  },
  {
    id: uuidv4(),
    name: "Administration",
    skills: [
      "Office Management",
      "Administrative Support",
      "Calendar Management",
      "Meeting Coordination",
      "Document Management",
      "Travel Arrangements",
      "Customer Service",
      "Event Planning",
      "Data Entry",
      "Records Management",
      "Administrative Procedures",
      "Expense Reporting",
      "Communication Skills",
      "Office Supplies Management",
      "Filing Systems",
      "Project Coordination",
      "Time Management",
      "Reporting",
      "Confidentiality",
      "Organizational Skills",
      "Scheduling",
      "Reception Duties",
      "Office Software (e.g., MS Office)",
      "Procedure Development",
      "Staff Supervision",
      "Administrative Project Management",
      "Meeting Minutes",
      "Correspondence Management",
      "Administrative Procedures",
      "Office Efficiency",
      "Client Interaction",
      "Team Collaboration",
      "Administrative Policy Implementation",
      "Office Communication",
    ],
  },
  {
    id: uuidv4(),
    name: "Project Management",
    skills: [
      "Project Planning",
      "Resource Allocation",
      "Risk Management",
      "Project Scheduling",
      "Budget Management",
      "Stakeholder Management",
      "Task Management",
      "Scope Management",
      "Project Tracking",
      "Project Documentation",
      "Agile Methodology",
      "Scrum",
      "Waterfall Methodology",
      "Change Management",
      "Team Leadership",
      "Project Reporting",
      "Quality Assurance",
      "Project Execution",
      "Project Delivery",
      "Project Integration Management",
      "Cost Estimation",
      "Requirements Gathering",
      "Project Closure",
      "Time Management",
      "Conflict Resolution",
      "Project Communication",
      "Performance Monitoring",
      "Project Milestones",
      "Dependency Management",
      "Resource Management",
      "Project Budgeting",
      "Project Risk Assessment",
      "Client Relations",
      "Project Evaluation",
      "Issue Management",
      "Project Coordination",
      "Project Governance",
    ],
  },
  {
    id: uuidv4(),
    name: "IT Support",
    skills: [
      "Technical Support",
      "Troubleshooting",
      "Customer Service",
      "Hardware Maintenance",
      "Software Installation",
      "Network Configuration",
      "IT Security",
      "System Updates",
      "Help Desk Support",
      "User Training",
      "Technical Documentation",
      "Remote Support",
      "Incident Management",
      "Problem Resolution",
      "Service Desk Management",
      "IT Infrastructure",
      "Database Management",
      "System Monitoring",
      "Backup Management",
      "IT Compliance",
      "Technical Assistance",
      "Network Troubleshooting",
      "Operating Systems",
      "Application Support",
      "System Administration",
      "Service Level Agreements (SLAs)",
      "IT Asset Management",
      "User Account Management",
      "Security Patches",
      "Performance Tuning",
      "IT Troubleshooting",
      "Software Support",
      "Technical Escalation",
      "IT Support Services",
      "Network Security",
      "IT Support Processes",
    ],
  },
  {
    id: uuidv4(),
    name: "Logistics",
    skills: [
      "Supply Chain Management",
      "Inventory Management",
      "Warehousing",
      "Transportation Management",
      "Logistics Coordination",
      "Order Fulfillment",
      "Shipping & Receiving",
      "Demand Planning",
      "Procurement",
      "Vendor Management",
      "Warehouse Operations",
      "Distribution Management",
      "Route Optimization",
      "Logistics Strategy",
      "Fleet Management",
      "Supply Chain Optimization",
      "Process Improvement",
      "Logistics Analytics",
      "Cost Management",
      "Customs Compliance",
      "Logistics Technology",
      "Freight Management",
      "Stock Control",
      "Logistics Reporting",
      "Risk Management",
      "Sourcing",
      "Production Planning",
      "Cross-docking",
      "Capacity Planning",
      "Logistics Documentation",
      "Export/Import Regulations",
    ],
  },
  {
    id: uuidv4(),
    name: "Engineering Management",
    skills: [
      "Project Management",
      "Team Leadership",
      "Engineering Strategy",
      "Resource Allocation",
      "Technical Leadership",
      "Process Improvement",
      "Budget Management",
      "Engineering Design",
      "Risk Management",
      "Quality Assurance",
      "Engineering Processes",
      "Cross-functional Team Coordination",
      "Performance Management",
      "Product Development",
      "Stakeholder Management",
      "Change Management",
      "Technical Roadmaps",
      "Mentoring and Coaching",
      "Engineering Best Practices",
      "Agile Methodology",
      "Scrum",
      "Technical Documentation",
      "Operational Efficiency",
      "Project Scheduling",
      "Cost Estimation",
      "Engineering Metrics",
      "Compliance",
      "Innovation Management",
      "Technical Problem Solving",
      "Engineering Tools and Technologies",
      "Strategic Planning",
    ],
  },
  {
    id: uuidv4(),
    name: "Consulting",
    skills: [
      "Client Management",
      "Needs Assessment",
      "Problem Solving",
      "Strategic Planning",
      "Business Analysis",
      "Project Management",
      "Solution Design",
      "Market Research",
      "Data Analysis",
      "Change Management",
      "Risk Assessment",
      "Process Improvement",
      "Presentation Skills",
      "Stakeholder Engagement",
      "Advisory Services",
      "Proposal Writing",
      "Consulting Methodologies",
      "Cost-Benefit Analysis",
      "Operational Efficiency",
      "Performance Metrics",
      "Client Relationship Management",
      "Negotiation",
      "Industry Knowledge",
      "Project Delivery",
      "Strategic Recommendations",
      "Workshop Facilitation",
      "Business Development",
      "Analytical Thinking",
      "Consulting Tools",
      "Leadership",
      "Report Writing",
      "Client Presentations",
    ],
  },
  {
    id: uuidv4(),
    name: "Research and Development",
    skills: [
      "Experimental Design",
      "Data Analysis",
      "Research Methodologies",
      "Project Management",
      "Innovation Management",
      "Prototyping",
      "Technical Research",
      "Product Development",
      "Literature Review",
      "Research Documentation",
      "Statistical Analysis",
      "Hypothesis Testing",
      "Experimental Techniques",
      "Research Strategy",
      "Grant Writing",
      "Collaboration",
      "Technical Reporting",
      "Research Tools",
      "Data Collection",
      "Technical Writing",
      "Cross-disciplinary Research",
      "Intellectual Property",
      "Trend Analysis",
      "Market Research",
      "Technology Transfer",
      "Research Ethics",
      "Scientific Computing",
      "Project Planning",
      "Research Presentation",
      "Innovation Processes",
      "Knowledge Management",
    ],
  },
  {
    id: uuidv4(),
    name: "Business Development",
    skills: [
      "Lead Generation",
      "Sales Strategy",
      "Market Analysis",
      "Client Acquisition",
      "Relationship Building",
      "Negotiation",
      "Strategic Partnerships",
      "Sales Forecasting",
      "Opportunity Identification",
      "Business Strategy",
      "Networking",
      "Proposal Development",
      "Market Research",
      "Account Management",
      "Customer Insights",
      "Revenue Growth",
      "Competitive Analysis",
      "Product Positioning",
      "Business Planning",
      "Deal Closure",
      "Client Relationship Management",
      "Sales Enablement",
      "Value Proposition",
      "Client Retention",
      "Business Proposals",
      "Partnership Development",
      "Sales Reporting",
      "Strategic Account Management",
      "Performance Metrics",
      "Business Negotiation",
      "Market Expansion",
    ],
  },
  {
    id: uuidv4(),
    name: "Public Relations",
    skills: [
      "Media Relations",
      "Press Releases",
      "Public Speaking",
      "Crisis Management",
      "Brand Management",
      "Communication Strategy",
      "Event Planning",
      "Media Outreach",
      "Content Creation",
      "Social Media Management",
      "Publicity",
      "Stakeholder Engagement",
      "Reputation Management",
      "Community Relations",
      "Press Kit Development",
      "Internal Communications",
      "Public Affairs",
      "Editorial Writing",
      "Media Monitoring",
      "Strategic Communication",
      "Public Relations Campaigns",
      "Influencer Relations",
      "Brand Messaging",
      "Message Development",
      "PR Metrics",
      "Media Training",
      "Crisis Communication",
      "Storytelling",
      "Releases and Announcements",
      "Audience Analysis",
      "Strategic PR Planning",
    ],
  },
  {
    id: uuidv4(),
    name: "Product Design",
    skills: [
      "User Experience Design (UX)",
      "User Interface Design (UI)",
      "Prototyping",
      "Wireframing",
      "Interaction Design",
      "Visual Design",
      "Design Thinking",
      "Human-Centered Design",
      "User Research",
      "Usability Testing",
      "Design Systems",
      "Brand Identity",
      "Typography",
      "Color Theory",
      "Responsive Design",
      "Sketch",
      "Figma",
      "Adobe Creative Suite",
      "Creative Problem Solving",
      "Design Prototyping",
      "Design Documentation",
      "Cross-Platform Design",
      "Product Aesthetics",
      "Design Trends",
      "Collaboration with Developers",
      "User Flow Design",
      "Design Tools",
      "Customer Journey Mapping",
      "Design Critique",
      "Design Validation",
      "Product User Testing",
    ],
  },
  {
    id: uuidv4(),
    name: "Creative",
    skills: [
      "Creative Direction",
      "Graphic Design",
      "Visual Communication",
      "Content Creation",
      "Brand Identity",
      "Storytelling",
      "Concept Development",
      "Creative Writing",
      "Art Direction",
      "Multimedia Design",
      "Photography",
      "Video Production",
      "Creative Strategy",
      "Digital Illustration",
      "Animation",
      "Creative Problem Solving",
      "Design Thinking",
      "Visual Storytelling",
      "Creative Research",
      "Artistic Skills",
      "Creative Collaboration",
      "Creative Editing",
      "Brand Development",
      "Marketing Campaigns",
      "Advertising",
      "Creative Projects Management",
      "Visual Branding",
      "Creative Process Management",
      "Creative Innovation",
      "Creative Trends",
      "Content Strategy",
      "Artistic Direction",
    ],
  },
];

module.exports = {
  skills,
};
